packages:
  - "packages/*"

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - graph-explorer
  - "@zazuko/*"

allowBuilds:
  "@fortawesome/fontawesome-common-types": false
  "@fortawesome/free-solid-svg-icons": false
  esbuild: true
  protobufjs: false
